### ISSUE TITLE
Wrong SSL address

### ISSUE THREAD

**Issue by aalextok** [Develandoo/yii2-push-notification#1]
When using APNS sandbox environment (Push::APNS_ENVIRONMENT_SANDBOX), the following ssl path is generated: ssl://gateway.push.sandbox.apple.com:2195. This produce an error: "stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known".
If I change path to ssl://gateway.sandbox.push.apple.com:2195, notification is sent successfully.

**Comment by bit-crafter** [comment]
Thank you for your issue submission.
It's already fixed.
